---
title: "1.2_Conventional_Linear_Mixed_Model"
author: "Tianjing Zhao"
date: "August 26, 2018"
output: rmarkdown::github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Install package
```{r}
library(devtools)
install_github("zhaotianjing/JWASr")
```
### load package
```{r}
library("JWASr")
```
### set up (windows user)
```{r}
path_libjulia = "C:/Users/ztjsw/AppData/Local/Julia-0.7.0/bin/libjulia.dll"
JWASr::jwasr_setup_win(path_libjulia)
```
For Mac user, run one line "JWASr::jwasr_setup()" to setup.


### build model
```{r}
model_equation ="y1 = intercept + x1 + x3
                  y2 = intercept + x1 + x2 + x3
                  y3 = intercept + x1 + x1*x3 + x2"
R = diag(3)

model = JWASr::build_model(model_equation,R)   #build "model" in Julia
```


### data
```{r}
phenotypes = JWASr::phenotypes
phenotypes
```

### set covariate
```{r}
JWASr::ran_julia('set_covariate(model,"x1")')
```

### set random
```{r}
JWASr::assign("G1",diag(2))
JWASr::ran_julia('set_random(model,"x2",G1)')
```


### run
```{R}
JWASr::ran_julia('outputMCMCsamples(model,"x1")')
out = JWASr::runMCMC(data = phenotypes, chain_length=5000, output_samples_frequency=100)
out
```
