---
title: "2.1_Linear_Additive_Genetic_Model"
author: "Tianjing Zhao"
date: "August 27, 2018"
output: rmarkdown::github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


### Install package
library(devtools)
install_github("zhaotianjing/JWASr")

### load package
```{r}
library("JWASr")
```
### set up (windows user)
```{r}
path_libjulia = "C:/Users/ztjsw/AppData/Local/Julia-0.7.0/bin/libjulia.dll"
jwasr_setup_win(path_libjulia)
```
For Mac user, run one line "JWASr::jwasr_setup()" to setup.


### data
```{r}
phenotypes = phenotypes #build-in data

ped_path = "D:\\JWASr\\data\\pedigree.txt"
get_pedigree(ped_path, separator=',', header=T)  #build "pedigree" in Julia
```


### build model
```{r}
model_equation = "y1 = intercept + x1*x3 + x2 + x3 + ID + dam";
R = 1.0
model = build_model(model_equation, R) #build "model" in Julia
```

### set covariate
```{r}
set_covariate("x1")
```

### set random
```{r}
G1 = 1.0
set_random("x2",G1) #pedigree = FALSE in default
```
```{r}
G2 = diag(2)
set_random("ID dam", G2, pedigree = TRUE) #use pedigree
```

### run
```{r}
outputMCMCsamples("x2")
out = runMCMC(data = phenotypes, chain_length = 5000, output_samples_frequency = 100)
out
```

