---
title: "2.2_Linear_Additive_Genetic_Model"
author: "Tianjing Zhao"
date: "August 27, 2018"
output: rmarkdown::github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Install package
```{r}
library(devtools)
install_github("zhaotianjing/JWASr")
```
### set up (windows user)
```{r}
path_libjulia = "C:/Users/ztjsw/AppData/Local/Julia-0.7.0/bin/libjulia.dll"
JWASr::jwasr_setup_win(path_libjulia)
```
For Mac user, run one line "JWASr::jwasr_setup()" to setup.


### build model
```{r}
model_equation ="y1 = intercept + x1 + x3 + ID + dam
                  y2 = intercept + x1 + x2 + x3 + ID
                  y3 = intercept + x1 + x1*x3 + x2 + ID"
R = diag(3)

model = JWASr::build_model(model_equation, R)  #build "model" in Julia
```

### data
```{r}
phenotypes = JWASr::phenotypes

ped_path = "D:\\JWASr\\data\\pedigree.txt"
JWASr::get_pedigree(ped_path, separator=',', header=T)  #build "pedigree" in Julia
```


### set covariate
```{r}
JWASr::assign("x1","x1")
JWASr::ran_julia("set_covariate(model,x1)")
```


### set random
```{r}
JWASr::assign("G1", diag(2))
JWASr::assign("x2","x2")
JWASr::ran_julia("set_random(model,x2,G1)")
```
```{r}
JWASr::assign("G2",diag(4))
JWASr::assign("ID_dam","ID dam")
JWASr::ran_julia("set_random(model,ID_dam,pedigree,G2)")
```

### run
```{r}
JWASr::ran_julia("outputMCMCsamples(model,x2)")
out = JWASr::runMCMC(model,phenotypes,chain_length=5000,output_samples_frequency=100, outputEBV = 1)   #outputEBV  = 1: true; 0: false
```

### select result "EBV_y2"
```{r}
out$EBV_y2
```
Or "out[1]"

### all results
```{r}
out
```

