---
title: "3.1_Genomic_Linear_Mixed_Model"
author: "Tianjing Zhao"
date: "August 27, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


### Install package
```{r}
library(devtools)
install_github("zhaotianjing/JWASr")
```

### set up (windows user)
```{r}
path_libjulia = "C:/Users/ztjsw/AppData/Local/Julia-0.7.0/bin/libjulia.dll"
JWASr::jwasr_setup_win(path_libjulia)
```
For Mac user, run one line "JWASr::jwasr_setup()" to setup.


### data
```{r}
phenotypes = JWASr::phenotypes

ped_path = "D:\\JWASr\\data\\pedigree.txt"
JWASr::get_pedigree(ped_path, separator=',', header=T)  #build "pedigree" in Julia
```

### build model
```{r}
model_equation = "y1 = intercept + x1*x3 + x2 + x3 + ID + dam";
R = 1.0
model = JWASr::build_model(model_equation,R) #build "model" in Julia
```

### set covariate
```{r}
JWASr::assign("x1","x1")
JWASr::ran_julia("set_covariate(model,x1);")
```


### set random
```{r}
JWASr::assign("G1", 1.0)
JWASr::assign("x2","x2")
JWASr::ran_julia("set_random(model,x2,G1)")
```
```{r}
JWASr::assign("G2",diag(2))
JWASr::assign("ID_dam","ID dam")
JWASr::ran_julia("set_random(model,ID_dam,pedigree,G2)")
```

### add genotypes
```{r}
G3 = 1.0
geno_path = "D:/JWASr/data/genotypes.txt"

JWASr::add_genotypes(geno_path, G3)  #separator=',' is default
```


### run
```{r}
JWASr::ran_julia("outputMCMCsamples(model,x2)")
out = JWASr::runMCMC(model, phenotypes, methods = "BayesC", estimatePi = 1, chain_length = 5000, output_samples_frequency = 100)  #estimatePi = 1 : true; 0: false
out
```

