---
title: "3.2_Genomic_Linear_Mixed_Model"
author: "Tianjing Zhao"
date: "August 27, 2018"
output: rmarkdown::github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Install package
```{r}
library(devtools)
install_github("zhaotianjing/JWASr")
```

### set up (windows user)
```{r}
path_libjulia = "C:/Users/ztjsw/AppData/Local/Julia-0.7.0/bin/libjulia.dll"
JWASr::jwasr_setup_win(path_libjulia)
```
For Mac user, run one line "JWASr::jwasr_setup()" to setup.


### data
```{r}
phenotypes = JWASr::phenotypes

ped_path = "D:\\JWASr\\data\\pedigree.txt"
JWASr::get_pedigree(ped_path, separator=',', header=T)  #build "pedigree" in Julia
```

### build model
```{r}
model_equation ="y1 = intercept + x1 + x3 + ID + dam
                  y2 = intercept + x1 + x2 + x3 + ID
                  y3 = intercept + x1 + x1*x3 + x2 + ID"
R = diag(3)
model = JWASr::build_model(model_equation,R)
```

### set covariate
```{r}
JWASr::ran_julia('set_covariate(model,"x1");')
```

### set random
```{r}
JWASr::assign("G1", diag(2))
JWASr::ran_julia('set_random(model,"x2",G1)')
```
```{r}
JWASr::assign("G2",diag(4))
JWASr::ran_julia('set_random(model,"ID dam",pedigree,G2)')
```

### add genotypes
```{r}
G3 = diag(3)
geno_path = "D:/JWASr/data/genotypes.txt"

JWASr::add_genotypes(geno_path, G3)  #separator=',' is default
```


### run
```{r}
JWASr::ran_julia('outputMCMCsamples(model,"x2")')
out = JWASr::runMCMC(model, phenotypes, methods = "BayesC", estimatePi = TRUE, chain_length = 5000, output_samples_frequency = 100)
```

### select result "Posterior mean of Pi"
```{r}
 out$`Posterior mean of Pi`
```

### all results
```{r}
out
```
